# Generated by Django 4.2.3 on 2024-12-04 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_livenews', '0004_livenews_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livenews',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterField(
            model_name='livenews',
            name='img_url',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='livenews',
            name='title',
            field=models.CharField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='livenews',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('liveblog', 'Live Blog'), ('video', 'Video')], max_length=200),
        ),
        migrations.AlterField(
            model_name='livenews',
            name='web_url',
            field=models.URLField(max_length=600),
        ),
        migrations.AddIndex(
            model_name='livenews',
            index=models.Index(fields=['news_category'], name='core_livene_news_ca_888d03_idx'),
        ),
        migrations.AddIndex(
            model_name='livenews',
            index=models.Index(fields=['publication_date'], name='core_livene_publica_0e7f7a_idx'),
        ),
    ]
