# Generated by Django 4.2.3 on 2024-12-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_livenews', '0006_newscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenews',
            name='confidence',
            field=models.FloatField(default=0.84),
        ),
    ]
