# Generated by Django 4.2.3 on 2024-12-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_livenews', '0007_livenews_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livenews',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Live News', 'verbose_name_plural': 'Live News'},
        ),
        migrations.AlterField(
            model_name='livenews',
            name='web_url',
            field=models.URLField(max_length=600, unique=True),
        ),
        migrations.AddIndex(
            model_name='livenews',
            index=models.Index(fields=['web_url'], name='core_livene_web_url_d8bf8a_idx'),
        ),
    ]
