# Generated by Django 4.2.3 on 2024-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_livenews', '0008_alter_livenews_options_alter_livenews_web_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livenews',
            name='img_url',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
